name: Deploy to EKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  # ✅ Fix: this line is mandatory
        audience: sts.amazonaws.com            # Optional for OIDC (keep or remove as needed)

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to ECR
      run: |
        set -e
        ECR_URI=$(aws ecr describe-repositories \
          --repository-names ${{ secrets.ECR_REPOSITORY }} \
          --region ${{ secrets.AWS_REGION }} \
          --query 'repositories[0].repositoryUri' \
          --output text)

        echo "ECR_URI=$ECR_URI"
        docker build -t $ECR_URI:$IMAGE_TAG .
        docker push $ECR_URI:$IMAGE_TAG
        echo "ECR_IMAGE=$ECR_URI:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.30.1  # Set to your desired version

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        sed "s|<ECR_IMAGE_URI>|${{ env.ECR_IMAGE }}|g" deployment.yaml > deployment-final.yaml
        kubectl apply -f deployment-final.yaml
        kubectl apply -f service.yaml
