name: Deploy PHP App

on:
  push:
    branches:
      - main   # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up PHP (with extensions)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'   # Change if your app uses another PHP version
          extensions: mbstring, pdo, pdo_mysql, intl, zip, curl
          coverage: none

      # 3. Install Composer
      - name: Install dependencies with Composer
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      # 4. Run tests (optional)
      - name: Run PHPUnit tests
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit
          fi

      # 5. Deploy via SSH
      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/your-app   # Change to your server path
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force || true
            sudo systemctl restart apache2
